name: Use Action
description: Allows the context to use private github actions within the workflow context
author: Concept-Art-House

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  github-repository:
    description: "The GitHub repostiory. Example: `octocat/hello-world`"
    required: true
  actions-directory:
    description: The default location 
    default: ".actions"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        if [ -z "$GH_REPOSITORY" ]; then
          echo "GH_REPOSITORY is not set"
          exit 1
        fi

        echo "GH_REPOSITORY: $GH_REPOSITORY"

        if [[ "$GH_REPOSITORY" =~ "@" ]]; then
          RELEASE_TAG="${GH_REPOSITORY##*@}"
          GH_REPOSITORY="${GH_REPOSITORY%@*}"
        fi

        GITHUB_OWNER="${GH_REPOSITORY%%/*}"
        GITHUB_REPO="${GH_REPOSITORY#*/}"

        echo "::set-output name=release-tag::$RELEASE_TAG"
        echo "::set-output name=github-owner::$GITHUB_OWNER"
        echo "::set-output name=github-repo::$GITHUB_REPO"

      id: setup
      shell: bash
      env:
        GH_REPOSITORY: ${{ inputs.github-repository }}
    - run: |
        join_paths() {
          (IFS=/; echo "$*" | tr -s /)
        }

        setup_download_directory() {
          local dir=$1

          mkdir -p $dir
        }

        download_action() {
          local url=$1
          local token=$2
          local dir=$3

          curl "$url" -sL --user "$token:x-oauth-basic" --output - | tar -xzf - -C $dir --strip-components=1 # Extract the archive to the actions directory
        }

        DIRECTORY_PATH=$(join_paths $ACTIONS_DIRECTORY $GITHUB_OWNER $GITHUB_REPO@$RELEASE_TAG)

        setup_download_directory $DIRECTORY_PATH
        download_action "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/tarball/$RELEASE_TAG" "$GITHUB_TOKEN" "$DIRECTORY_PATH"

      env:
        ACTIONS_DIRECTORY: ${{ inputs.actions-directory }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_OWNER: ${{ steps.setup.outputs.github-owner }}
        GITHUB_REPO: ${{ steps.setup.outputs.github-repo }}
        RELEASE_TAG: ${{ steps.setup.outputs.release-tag }}
      shell: bash